export const AUSTRALIAN_RULES_GOAL_POST_SPACING_METRES = 6.4;
export const AUSTRALIAN_RULES_BEHIND_POST_OFFSET_METRES = 6.4;
export const AUSTRALIAN_RULES_FULL_GOAL_WIDTH_METRES =
  AUSTRALIAN_RULES_GOAL_POST_SPACING_METRES + AUSTRALIAN_RULES_BEHIND_POST_OFFSET_METRES * 2;
export const AUSTRALIAN_RULES_GOAL_POST_HEIGHT_METRES = 6;
export const AUSTRALIAN_RULES_BEHIND_POST_HEIGHT_METRES = 3;
export const AUSTRALIAN_RULES_FIFTY_ARC_METRES = 50;
export const AUSTRALIAN_RULES_CENTRE_SQUARE_METRES = 50;
export const AUSTRALIAN_RULES_OUTER_CIRCLE_DIAMETER_METRES = 10;
export const AUSTRALIAN_RULES_INNER_CIRCLE_DIAMETER_METRES = 3;
export const AUSTRALIAN_RULES_GOAL_SQUARE_DEPTH_METRES = 9;
export const CRICKET_PITCH_LENGTH_METRES = 20.12;
export const CRICKET_PITCH_WIDTH_METRES = 3.05;
export const CRICKET_BOWLING_CREASE_LENGTH_METRES = 2.64;
export const CRICKET_POPPING_CREASE_LENGTH_METRES = 3.66;
export const CRICKET_POPPING_CREASE_OFFSET_METRES = 1.22;
export const CRICKET_RETURN_CREASE_LENGTH_METRES = 2.44;
export const CRICKET_STUMP_HEIGHT_METRES = 0.711;
export const CRICKET_WICKET_WIDTH_METRES = 0.229;
export const BASKETBALL_RIM_HEIGHT_METRES = 3.05;
export const BASKETBALL_BACKBOARD_WIDTH_METRES = 1.83;

export function footballPostLocalOffsets(totalWidth: number): [number, number, number, number] {
  const goalPostHalfWidth = totalWidth / 6;
  const behindPostHalfWidth = totalWidth / 2;
  return [-behindPostHalfWidth, -goalPostHalfWidth, goalPostHalfWidth, behindPostHalfWidth];
}
